name: 'Setup IDA Pro'
description: 'Setup IDA Pro'
author: 'dumbasPL'

inputs:
  download-link:
    description: 'Download link to the IDA Pro installer (appropriate for the runner OS)'
    required: true
  overlay-links:
    description: 'Newline-separated list of ZIP files to extract over the IDA Pro installation (license, plugins, etc.)'
    required: false
  install-command:
    description: "Additional BASH command to run after extracting the overlay files (if the overlay files don't extract to the correct location)"
    required: false
  use-cloud-cache:
    description: 'Use GitHub Actions Cloud Cache instead of tool cache'
    required: false
    default: 'true'

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'download'
  color: 'blue'